#!/bin/bash

# Path to the file where you want to change N_SLOTS
TARGET_FILE="/home/luis/Github/cva6/corev_apu/wg_checker/packages/wg_checker/wg_checker_reg_pkg.sv"

# Path to the file to change the constraints
CLK_GEN_FILE="/home/luis/Github/cva6/corev_apu/fpga/xilinx/xlnx_clk_gen/tcl/run.tcl"
CONST_FILE="/home/luis/Github/cva6/corev_apu/fpga/constraints/genesys-2.xdc"

# Path to the report file generated by make
REPORT_FILE="/home/luis/Github/cva6/corev_apu/fpga/reports/ariane.utilization.rpt"
REPORT_FILE_TIMING="/home/luis/Github/cva6/corev_apu/fpga/reports/wg_checker_violations.rpt"

# Output folder
OUTPUT_DIR="./utilization_script"
OUTPUT_DIR_TIMING="./timing_script"

# Create output directory if it doesn't exist


# Start with 1 and double each time up to 32
for N in 2 4; do
    mkdir -p "${OUTPUT_DIR}_${N}"
    mkdir -p "${OUTPUT_DIR_TIMING}_${N}"
    echo "Setting N_SLOTS = $N"

    # Replace the line in the target file
    sed -i "s/parameter int N_SLOTS = [0-9]\+;/parameter int N_SLOTS = $N;/" "$TARGET_FILE"
    
    for FREQ in 270 280 290 ; do
        make -C ./corev_apu/fpga clean

        PERIOD=$(awk "BEGIN {printf \"%.3f\", 1000/$FREQ}")
        echo "Setting frequency = $FREQ and period = $PERIOD"

        # Replace the line in the target file
        sed -i -E "/^[[:space:]]*-period[[:space:]]+[0-9.]+[[:space:]]*\\\\[[:space:]]*$/ s/(-period[[:space:]]+)[0-9.]+/\1$PERIOD/" "$CONST_FILE"
        sed -i "s/CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {[0-9]\+}/CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {$FREQ}/" "$CLK_GEN_FILE"
           
        # Run the build command
        make fpga target=cv64a6_imafdch_sv39

        # Copy the utilization report to the output folder with a unique name
        cp "$REPORT_FILE_TIMING" "${OUTPUT_DIR_TIMING}_${N}/timing.freq_$FREQ.rpt"
        
        if [ "$FREQ" -eq 270 ]; then
            # Copy the utilization report to the output folder with a unique name
            cp "$REPORT_FILE" "${OUTPUT_DIR}_${N}/ariane.utilization.N_SLOTS_$N.rpt"
        fi
    done

    echo "Finished iteration with N_SLOTS = $N"
done

echo "All done."
