#!/bin/bash

# Path to the file to change the constraints
CLK_GEN_FILE="/home/luis/Github/cva6/corev_apu/fpga/xilinx/xlnx_clk_gen/tcl/run.tcl"
CONST_FILE="/home/luis/Github/cva6/corev_apu/fpga/constraints/genesys-2.xdc"

# Path to the report file generated by make
REPORT_FILE="/home/luis/Github/cva6/corev_apu/fpga/reports/wg_checker_violations.rpt"

# Output folder
OUTPUT_DIR="./timing_script"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

for N in 200 300 400; do
    make -C ./corev_apu/fpga clean

    PERIOD=$(awk "BEGIN {printf \"%.3f\", 1000/$N}")
    echo "Setting frequency = $N and period = $PERIOD"

    # Replace the line in the target file
    sed -i -E "/^[[:space:]]*-period[[:space:]]+[0-9.]+[[:space:]]*\\\\[[:space:]]*$/ s/(-period[[:space:]]+)[0-9.]+/\1$PERIOD/" "$CONST_FILE"
    sed -i "s/CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {[0-9]\+}/CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {$N}/" "$CLK_GEN_FILE"
       
    # Run the build command
    make fpga target=cv64a6_imafdch_sv39

    # Copy the utilization report to the output folder with a unique name
    cp "$REPORT_FILE" "$OUTPUT_DIR/timing.freq_$N.rpt"

    echo "Finished iteration with freq = $N"
done

echo "All done."
