#!/bin/bash

# Path to the file where you want to change N_SLOTS
TARGET_FILE="/home/luis/Github/cva6/corev_apu/wg_checker/packages/wg_checker/wg_checker_reg_pkg.sv"

# Path to the report file generated by make
REPORT_FILE="/home/luis/Github/cva6/corev_apu/fpga/reports/ariane.utilization.rpt"

# Output folder
OUTPUT_DIR="./utilization_script"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Start with 1 and double each time up to 32
for N in 1 2 4 16 32; do
    echo "Setting N_SLOTS = $N"

    # Replace the line in the target file
    sed -i "s/parameter int N_SLOTS = [0-9]\+;/parameter int N_SLOTS = $N;/" "$TARGET_FILE"

    # Run the build command
    make fpga target=cv64a6_imafdch_sv39

    # Copy the utilization report to the output folder with a unique name
    cp "$REPORT_FILE" "$OUTPUT_DIR/ariane.utilization.N_SLOTS_$N.rpt"

    echo "Finished iteration with N_SLOTS = $N"
    
    make -C ./corev_apu/fpga clean
done

echo "All done."
