#!/bin/bash

# Path to the file where you want to change N_SLOTS
TARGET_FILE="/home/luis/github/cva6/corev_apu/wg_checker/packages/wg_checker/wg_checker_reg_pkg.sv"

# Path to the report file generated by make
REPORT_FILE="./corev_apu/fpga/reports/ariane.utilization.rpt"

# Output folder
OUTPUT_DIR="./utilization_wid"


# Replace the line in the target file
sed -i "s/parameter int N_SLOTS = [0-9]\+;/parameter int N_SLOTS = 8;/" "$TARGET_FILE"

for N in 1 2 4 8 16 32; do
    	mkdir -p "${OUTPUT_DIR}/${N}"
	echo "Setting RRIDS = $N"

    	# Replace the line in the target file
    	sed -i "s/parameter int N_WIDS = [0-9]\+;/parameter int N_WIDS = $N;/" "$TARGET_FILE"
    
	make -C ./corev_apu/fpga clean
   
	# Run the build command
	make fpga target=cv64a6_imafdch_sv39

        
	# Copy the utilization report to the output folder with a unique name
	cp "$REPORT_FILE" "${OUTPUT_DIR}/${N}/ariane.utilization.N_WIDS_$N.rpt"
	cp "$BITSTREAM_FILE" "${OUTPUT_DIR}/${N}/ariane_xilinx_$N.bit"

    echo "Finished iteration with WIDS = $N"
done

echo "All done."
